services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_DB: database
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      CHECK_EMAIL_DELIVERABILITY: false
    ports:
      - "15432:80"
    depends_on:
      postgres:
        condition: service_healthy
    user: root
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  postgres_data:
    driver: local
