# Generated by Django 5.1 on 2024-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saber', '0002_college_period_highschool_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='period',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='period',
        ),
        migrations.AddField(
            model_name='collegestudent',
            name='period',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschoolstudent',
            name='period',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
