# Generated by Django 5.1 on 2024-09-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saber', '0007_alter_collegestudent_mod_citizenship_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_periods', to='saber.period'),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_periods', to='saber.period'),
        ),
    ]
