query collegeStudents($collegeId: ID!, $pageSize: Int, $page: Int) {
    collegeStudents(collegeId: $collegeId, pageSize: $pageSize, page: $page) {
        MODQuantitativeReasoning
        MODWrittenCommunication
        MODCriticalReading
        MODEnglish
        MODCitizenshipCompetences
    }
}
