query collegeStudentsCount(
    $departmentId: ID!
    $municipalityId: ID
    $collegeId: ID
) {
    collegeStudentsCount(
        departmentId: $departmentId
        municipalityId: $municipalityId
        collegeId: $collegeId
    )
}
