query highschoolStudents($highschoolId: ID!, $pageSize: Int, $page: Int) {
  highschoolStudents(highschoolId: $highschoolId, pageSize: $pageSize, page: $page) {
    PUNTEnglish
    PUNTMathematics
    PUNTNaturalSciences
    PUNTCriticalReading
    PUNTSocialCitizenship
    PUNTGlobal
  }
}