query highschoolStudentsCount(
    $departmentId: ID!
    $municipalityId: ID
    $highschoolId: ID
) {
    highschoolStudentsCount(
        departmentId: $departmentId
        municipalityId: $municipalityId
        highschoolId: $highschoolId
    )
}
