query highschoolStudents(
    $departmentId: ID!
    $municipalityId: ID
    $highschoolId: ID
    $pageSize: Int
    $page: Int
) {
    highschoolStudents(
        departmentId: $departmentId
        municipalityId: $municipalityId
        highschoolId: $highschoolId
        pageSize: $pageSize
        page: $page
    ) {
        PUNTEnglish
        PUNTMathematics
        PUNTNaturalSciences
        PUNTCriticalReading
        PUNTSocialCitizenship
        PUNTGlobal
    }
}
