# Generated by Django 5.1 on 2024-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saber', '0006_alter_college_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='MOD_CITIZENSHIP_COMPETENCES',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='MOD_CRITICAL_READING',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='MOD_ENGLISH',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='MOD_QUANTITATIVE_REASONING',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='MOD_WRITTEN_COMMUNICATION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_CRITICAL_READING',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_ENGLISH',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_GLOBAL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_MATHEMATICS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_NATURAL_SCIENCES',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='PUNT_SOCIAL_CITIZENSHIP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='period',
            field=models.CharField(max_length=10),
        ),
    ]
